FROM mcr.microsoft.com/windows:ltsc2019

RUN echo 10.0.0.5 my_website.com >> C:/Windows/System32/drivers/etc/hosts
COPY ./upload.ps1 C:/

ENTRYPOINT powershell.exe -ExecutionPolicy Bypass C:\upload.ps1