version: "3.3"

services:
  nginx:
    image: nginx:stable
    ports:
      - 443:443
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./nginx/cert/:/wwwroot/-/.cert/
      - ./nginx/www/:/wwwroot/-/pages/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always